server.port=8080

bluejay.datasource.url=jdbc:sqlite:data/db/bluejay.db
bluejay.datasource.driver-class-name=org.sqlite.JDBC

bluejay.security.jwt.secret=BlueJayJwtSecretKeyMustBeAtLeastThirtyTwoCharsLong
bluejay.security.jwt.expiration-seconds=3600

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:db/schema.sql
